name: PaperCardSignIn
version: '${project.version}'
main: cn.paper_card.sign_in.ThePlugin
api-version: '1.20'

folia-supported: true

author: Paper99

depend:
  - Database

softdepend:
  - PlayerCoins

commands:
  sign-in:
    permission: paper-card-sign-in.command

permissions:
  paper-card-sign-in.command:
    default: op